### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sv3nskie** [Linch1/Web3TokenCharting#3]
Hey Linch1, 

Thanks for sharing your code, I am building an own version and basically its almost done. I have a question about the pancakeswap functions, as I checked your code it seems that your code is only interested in 6 out of the 9 swap functions of the router contract. And I checked bsc and see the missing 3 functioms are used, but I do not fully understand if they are needed. Maybe we can get in touch if you have a few minutes spare time?

**Comment by Linch1** [comment]
Hey, i'm refactoring a bit the code since it was not really as good as i thought, i've already published a refaactoring of the scraper, now instead scraping each transaction block it listen for swap events

not only it is more efficient but it has a wider range of charting possibilities

if you want feel free to reach me on reddit https://www.reddit.com/user/Linch-1 :)

**Comment by Sv3nskie** [comment]
Thanks for the reply, I indeed saw you subscribing to logs instead to
blockheaders. Could you let me know from where you have the info of that?

I already made a system to create candlestick data, I only a bit confused
about what to do with some transactions.

As now I start getting reserves for each pair and later calculate mew price
after transaction. I want to try to use your log subscription if thats
faster. Not sure if logs have a deley.

**Comment by lordmen99** [comment]
Any demo this script online? i want see it

**Comment by Linch1** [comment]
@lordmen99 there aren't demo about this at the moment, actually i uploaded a frontend implementation for this, you can checkout it at https://github.com/Linch1/Web3TokenChartingDemo

There are some screen of this working
